proxy-providers:
  VPN:
    type: file
    path: "./📶providers📶.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 300
proxy-groups:
- name: Internet🌏
  type: select
  disable-udp: false
  use:
  - VPN
  url: http://www.gstatic.com/generate_204
  interval: '30'
direct:
  - DOMAIN-SUFFIX,my.im3
  - DOMAIN-SUFFIX,com.pure.indosat.com
  - DOMAIN-SUFFIX,indosat.net
  - DOMAIN-SUFFIX,rocksdb.org
  - DOMAIN-SUFFIX,whatsapp.com
  
  - DOMAIN-SUFFIX,m.me
  - DOMAIN-SUFFIX,oculus.com
  - DOMAIN-SUFFIX,oculuscdn.com
  - DOMAIN-SUFFIX,rocksdb.org
  - DOMAIN-SUFFIX,whatsapp.com
  - DOMAIN-SUFFIX,whatsapp.net
  - DOMAIN-SUFFIX,g.whatsapp.net
  - DOMAIN-SUFFIX,web.whatsapp.com
  - DOMAIN-SUFFIX,scontent.whatsapp.net
  - DOMAIN-SUFFIX,static.whatsapp.net
  - DOMAIN-SUFFIX,mmg.whatsapp.net
  - DOMAIN-SUFFIX,media.fbdj2-1.fna.whatsapp.net
  - DOMAIN-SUFFIX,media-xsp1-2.cdn.whatsapp.net
  - DST-PORT,3478
  - DST-PORT,4244
  - DST-PORT,5222
  - DST-PORT,5223
  - DST-PORT,5288
  - DST-PORT,5242
  - DST-PORT,5349
  - DST-PORT,34784
  - DST-PORT,45395
  - DST-PORT,50318
  - DST-PORT,59234
 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ''
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  nameserver:
  - 8.8.8.8
  - 1.0.0.1
  - https://dns.google/dns-query
  fallback:
  - 1.1.1.1
  - 8.8.4.4
  - https://cloudflare-dns.com/dns-query
  - 112.215.203.254
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 112.215.203.254
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
rules:
- MATCH,Internet🌏
